# Generated by Django 4.2.5 on 2024-06-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws2app', '0002_chat_group_delete_roominfo_chat_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
