# Generated by Django 4.2.5 on 2024-06-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws2app', '0003_chat_is_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userinfo', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='chat',
            name='is_online',
        ),
    ]
