# Generated by Django 4.2.5 on 2024-06-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws2app', '0004_userinfo_remove_chat_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='password',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
