# Generated by Django 4.2.5 on 2024-06-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws2app', '0005_userinfo_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='sender',
            field=models.CharField(default='', max_length=100),
        ),
    ]
