# Generated by Django 4.2.5 on 2024-07-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ws2app', '0006_chat_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_status',
            field=models.BooleanField(null=True),
        ),
    ]
